### ISSUE TITLE
Aqw_Zert style interacts with other styles

### ISSUE THREAD

**Issue by clauswilke** [camilleroux/fxhash-bridge#103]
As an example, see Estienne style rendered before and after Aqw_Zert has been rendered.

Before:
<img width="491" alt="Screen Shot 2022-02-20 at 10 12 55 PM" src="https://user-images.githubusercontent.com/4210929/154888128-2ca27bb9-57f2-4640-94fc-14cbdadbf3b5.png">

After:
<img width="490" alt="Screen Shot 2022-02-20 at 10 13 10 PM" src="https://user-images.githubusercontent.com/4210929/154888144-bf8dff75-88b7-4fb4-b4cd-b9d69b29c725.png">

@AqwUnderscoreZert Any unusual features that you use that need to be reset between drawing different styles? See here for all the things we're resetting already:
https://github.com/camilleroux/fxhash-bridge/blob/1c6cc2c513c15d9f7c8970a4533be5c4975c5852/src/index.js#L181-L191

**Comment by clauswilke** [comment]
These are candidates for things that need to be reset:
https://github.com/camilleroux/fxhash-bridge/blob/1c6cc2c513c15d9f7c8970a4533be5c4975c5852/src/styles/aqwunderscorezert.js#L20-L24

If I have to take a guess, it's probably the noise detail. Other styles use `noise()` without setting `noiseDetail()` first.

**Comment by AqwUnderscoreZert** [comment]
Wow thanks @clauswilke ! That one was not easy to catch! I'll add a function to reset all those settings! Thanks a lot!

**Comment by AqwUnderscoreZert** [comment]
Fixed for me! @camilleroux you can close this issue.
