### ISSUE TITLE
Style calling this._p5.pixelDensity(1) makes other styles blurry

### ISSUE THREAD

**Issue by elsifthen** [camilleroux/fxhash-bridge#21]
https://github.com/camilleroux/fxhash-bridge/blob/f977805e41c42bc358257b1f30979303d6d9aaa5/src/styles/frederative.js#L24
Not sure what the best fix is, maybe save the default pixelDensity and restore it before switching styles.

**Comment by camilleroux** [comment]
@frederative You're setting pixelDensity to 1. It can break other styles because it's persistent. Is it necessary? If yes, could you set it back to the default value at the end of you style maybe?

**Comment by frederative** [comment]
Didn't realize this is going to break everybody else's, sorry!  I am doing as @elsifthen suggests, please let me know if it keeps breaking your views as I don't really notice an issue on my screens.

**Comment by elsifthen** [comment]
It doesn't quite fix it because it only changes p5's internal state but doesn't resize the canvas. I'll comment more on the PR. Thanks for the quick investigation and fix!

**Comment by frederative** [comment]
@camilleroux --> hopefully commit dc95cada1d30263ca9245c254498a2305379649c resolves the issue
