### ISSUE TITLE
Some thoughts about the token description (FXHASH_INFO.md) and project in general

### ISSUE THREAD

**Issue by clauswilke** [camilleroux/fxhash-bridge#44]
I didn't want to just go in and edit without having a conversation first. Some thoughts:

- Do we want to include a link to the github repo? To me this is a major part of the story, we can actually go and look how all the different styles were implemented. And all the code is out in the open now, for everybody to see, so presumably the goal is to keep it that way.

- We should add some licensing terms to either the code or the art. Many people like the NFT license (https://www.nftlicense.org/). I personally have some reservations about it, so I don't use it in my own projects, but I won't be opposed to it if you like it for this project. Alternatively, putting all the code under CC-BY-NC-SA might be a good idea. I see several style authors have followed my lead and have already licensed their code that way.

- (Unrelated to token description) I think all style authors should add a clear copyright/license notice to their style, so there can be no legal confusion about what can and cannot be done with the code.

Those are the major points I can think of right now. I have some minor suggested edits to the token text that I think I'll just propose in a PR.

**Comment by camilleroux** [comment]
Thanks! 
- Yes 100% ok to include the link to the Github repo
- I'm not confortable to add a license to the whole project without the acceptation for every contributors. But that's a very good idea for a next collab. For that project, I'm OK with both licenses. If we can check that every contributors are OK with one of these, I'm OK to change. But we're more than 20 and the drop is in 2-3 days, it's going to be funky :)
- 100% ok for artists to add a license to their style while it's compatible with the README file.

**Comment by clauswilke** [comment]
> I'm not confortable to add a license to the whole project without the acceptation for every contributors.

In that case maybe add a license to the framework code and state that contributing artists hold the copyright to their specific styles. I can rewrite the license PR accordingly.

**Comment by camilleroux** [comment]
Yes, it's probably the best solution with a dead line in less than 2 days :)
Thanks!

**Comment by clauswilke** [comment]
I think this issue has mostly been addressed now.
