### ISSUE TITLE
Lunarean style somehow interferes with other styles

### ISSUE THREAD

**Issue by clauswilke** [camilleroux/fxhash-bridge#49]
Easiest way to reproduce: Comment out all styles except Lunarean and Boilerplate, then cycle between styles. After Lunarean has been drawn, Boilerplate turns very dark. Other styles are similarly affected.

**Comment by clauswilke** [comment]
I've narrowed it down to the `drawBgTriangles()` function. By itself, it is able to cause problems. I don't immediately see why. I have to run now but will continue looking later if nobody else figures it out first.

https://github.com/camilleroux/fxhash-bridge/blob/e41d17928d7e2e7ff62c682152a08ca248de5d79/src/styles/lunarean.js#L151-L186

**Comment by laurent-h** [comment]
some xxxMode() are missing in index.js to restore all defaults.
I'm also trying to figure it out...

**Comment by toshima** [comment]
Sorry about this, investigating it

**Comment by lunarean** [comment]
Sorry about this, investigating it

**Comment by laurent-h** [comment]
Reset strokeWeight in index ?
p5.strokeWeight(1)

**Comment by camilleroux** [comment]
Warning: resetting pixelDensity cleans the canvas :)
https://github.com/processing/p5.js/blob/v1.4.1/src/core/environment.js#L598

**Comment by lunarean** [comment]
> Reset strokeWeight in index ? p5.strokeWeight(1)
> 
> Resetting pixelDensity would also be a good idea: p5.pixelDensity(window.devicePixelRatio)

nice! resetting strokeWeight seems to fix it

I can submit a fix adding those two lines to index.js

**Comment by clauswilke** [comment]
@lunarean While you're at it, I would also suggest to move this line down to after all the style settings have been reset, just to be save:

https://github.com/camilleroux/fxhash-bridge/blob/71be0af75ba44cde67c365d1df552b6d8d0f54f1/src/index.js#L151

**Comment by clauswilke** [comment]
Basically, move to right before here:
https://github.com/camilleroux/fxhash-bridge/blob/71be0af75ba44cde67c365d1df552b6d8d0f54f1/src/index.js#L163
