### ISSUE TITLE
bfos style is not dimension-less

### ISSUE THREAD

**Issue by camilleroux** [camilleroux/fxhash-bridge#55]
Hi @bfos,

The point sizes are not proportional to this._s, so your style is not dimension-less currently:
https://github.com/camilleroux/fxhash-bridge/blob/49de348d0e2be4b0153bb533fd71a77b47624d15/src/styles/bfos.js#L109

**Comment by bfos** [comment]
I'm not sure if I'm fully understanding this issue.  I do think that the point positions (ix and iy) are relative to this._s as their values are derived in the preceding lines of code which do use this._s in the calculation

I'm calculating where points can be placed horizontally for each brick by calculating the xStartPositionBasedOnY and xEndPositionBasedOnY.  

I've looked at this for a little while trying to understand what I would do differently, but it's not clear to me.  I also don't see anything off when I try different window sizes.  Am I still understanding incorrectly?

**Comment by bfos** [comment]
I do see that my points for my background grid are not dimensionless.  I'll work on that in the meantime.

**Comment by bfos** [comment]
I did find a way of looking at my points as not being dimensionless.  I've converted to using lines and sizing those based on a factor of this._s.
