### ISSUE TITLE
@ada-ada-ada-art  style is not dimension-less

### ISSUE THREAD

**Issue by camilleroux** [camilleroux/fxhash-bridge#57]
hi @ada-ada-ada-art 

Your style is not dimension-less currently. Here is an exemple
![image](https://user-images.githubusercontent.com/25977/154822719-4764e93e-374c-46ae-bc57-dc49271658dd.png)
![image](https://user-images.githubusercontent.com/25977/154822723-44edc344-cfe4-40d8-973c-0cfeb1b50953.png)

**Comment by ada-ada-ada-art** [comment]
@camilleroux

Aha. I was using `window.innerHeight` instead of `this._s` to control the text size. Should be fixed with PR #72. 

The dithering artefacts are really difficult for me to control, so I hope it's okay if they remain somewhat dimension chaotic.
