### ISSUE TITLE
david-esq  style is not dimension-less

### ISSUE THREAD

**Issue by camilleroux** [camilleroux/fxhash-bridge#59]
Hi @david-esq,

You're style is not dimension-less currently. It can even change of color when resized:
![image](https://user-images.githubusercontent.com/25977/154822792-c5573992-4373-4e73-9397-f3d1e07d4d86.png)
![image](https://user-images.githubusercontent.com/25977/154822797-5d48c2c6-d6ab-4786-93aa-9545a8af7f50.png)

**Comment by david-esq** [comment]
Sent a Pull request to fix colors & dimensions
