### ISSUE TITLE
Anaglyph-ic style is not dimension-less

### ISSUE THREAD

**Issue by camilleroux** [camilleroux/fxhash-bridge#60]
Hi @Anaglyph-ic 

Your style is not dimension-less. Here is an exemple:
![image](https://user-images.githubusercontent.com/25977/154822826-b9999405-9aad-421e-8041-b35fbb2140db.png)
![image](https://user-images.githubusercontent.com/25977/154822831-7c1ac557-c1a5-4606-8acb-f7c11dbc7cd3.png)

**Comment by Anaglyph-ic** [comment]
gotcha

-> https://github.com/camilleroux/fxhash-bridge/pull/70
