### ISSUE TITLE
phil_osophie style is not dimension-less

### ISSUE THREAD

**Issue by camilleroux** [camilleroux/fxhash-bridge#62]
Hi @pwambach 

Your style is not dimension-less. Here is an exemple: (same hash, different dimensions)
![image](https://user-images.githubusercontent.com/25977/154822961-d33d8903-0ab0-4ca0-9e5c-a6c768cf5855.png)
![image](https://user-images.githubusercontent.com/25977/154822967-5b620657-43f2-4646-9dff-598179793907.png)

**Comment by pwambach** [comment]
Thanks for the hint! Fixed it here https://github.com/camilleroux/fxhash-bridge/pull/79
<img width="728" alt="Screenshot 2022-02-20 at 16 47 36" src="https://user-images.githubusercontent.com/1611635/154851135-945c1f77-9134-4930-97f5-cdfa78066454.png">
<img width="215" alt="Screenshot 2022-02-20 at 16 47 26" src="https://user-images.githubusercontent.com/1611635/154851137-2b8ed14a-5441-4085-b8d7-203a45a81c9c.png">
