### ISSUE TITLE
Makio64 style is not dimension-less 

### ISSUE THREAD

**Issue by camilleroux** [camilleroux/fxhash-bridge#73]
Hi @Makio64,

You're style is not currently dimension-less (same result whatever the size):
![image](https://user-images.githubusercontent.com/25977/154842123-87423150-c49e-4777-b9e8-f19a9e1b2c52.png)
![image](https://user-images.githubusercontent.com/25977/154842129-46755c53-7282-4d9d-be31-ed1d721e0e23.png)

**Comment by Makio64** [comment]
fixed
