### ISSUE TITLE
mandyBrigwell style is not dimension-less

### ISSUE THREAD

**Issue by camilleroux** [camilleroux/fxhash-bridge#74]
Hi @mandyBrigwell,

You're style is not currently dimension-less (same result whatever the size):
![image](https://user-images.githubusercontent.com/25977/154842165-1b6ebcc2-2b10-4ce3-8789-3e8d0095b1c7.png)
![image](https://user-images.githubusercontent.com/25977/154842170-83378b1f-6f7d-4679-b03f-66a9692c790b.png)

**Comment by camilleroux** [comment]
You should replace all the `fxrand()` by this._p5.random().
We can't reset the seed the fxrand() in our case

**Comment by mandyBrigwell** [comment]
I've replaced it in my branch, but I'm not sure how to merge it with your branch. Give me a moment to do some googling…

**Comment by mandyBrigwell** [comment]
Ah, got it—I was looking in the wrong place.

**Comment by mandyBrigwell** [comment]
I think that does it now. I get the same for three test sizes.

![02Appended](https://user-images.githubusercontent.com/69047092/154842600-423f20ff-3481-4ccb-955a-fa3db9c94dd5.jpg)

**Comment by mandyBrigwell** [comment]
I've reworked the random code portion and pushed it. I'll let you decide whether to close this, as I don't want to be over-confident!

**Comment by camilleroux** [comment]
great! Thanks :)
