### ISSUE TITLE
JeresStyle style is not dimension-less

### ISSUE THREAD

**Issue by AqwUnderscoreZert** [camilleroux/fxhash-bridge#91]
Hi @jeremyschoenherr ,  some features are changing I'm resizing the image: (different sizes, same hash).

![image](https://user-images.githubusercontent.com/98602680/154869212-c51dac5d-4a20-4740-a46f-c8dc831f65de.png)

**Comment by jeremyschoenherr** [comment]
thank you! i’ll check it out in a bit! i’m not home or with my computer.

**Comment by jeremyschoenherr** [comment]
https://github.com/camilleroux/fxhash-bridge/pull/110
