### ISSUE TITLE
Devnull style is not dimension-less

### ISSUE THREAD

**Issue by AqwUnderscoreZert** [camilleroux/fxhash-bridge#92]
Hi @lostpunks 

Some buildings are chaging I'm resizing the image: (different sizes, same hash)

![image](https://user-images.githubusercontent.com/98602680/154869616-e71f6be8-ec04-4906-8052-2ed4afea5125.png)

**Comment by lostpunks** [comment]
Thanks. I'm on it.

**Comment by lostpunks** [comment]
Fixed two additional issues flagged by @camilleroux (same PR)
