### ISSUE TITLE
RVig style is not dimension-less

### ISSUE THREAD

**Issue by camilleroux** [camilleroux/fxhash-bridge#93]
Hi @rvig-art,

Your style is not 100% dimension-less. Lines seems to have constant size:
![image](https://user-images.githubusercontent.com/25977/154869672-25544e2b-fda1-4237-8e02-0a3e5150e6a0.png)
![image](https://user-images.githubusercontent.com/25977/154869678-3f457360-dc57-47ef-82fd-60cd7f46821a.png)

**Comment by rvig-art** [comment]
indeed... strokeWeight was missing in beforeDraw. it's now fixed and pull request created
