### ISSUE TITLE
David Esq style is not dimension-less

### ISSUE THREAD

**Issue by camilleroux** [camilleroux/fxhash-bridge#95]
Hi @david-esq ,

The blur seems to be more intense when the canvas size is small:
![image](https://user-images.githubusercontent.com/25977/154870022-f5bf9638-31e3-4775-9d03-15f33384defc.png)
![image](https://user-images.githubusercontent.com/25977/154870025-647f3b8f-9f2d-4470-b0ea-8cf207a849b8.png)

**Comment by david-esq** [comment]
Fixed.
